### ISSUE TITLE
[BUG?] Performance drop when looking in inventory with tons of items

### ISSUE THREAD

**Issue by Eeve2espeon** [TerrariaCraft/Issues#124] opened 2024-07-05 10:11 UTC
The problem: Somehow the game lowers my GPU usage which causes frames to drop whenever theres tons of items in the inventory. Usually the game runs at 120fps (full VSync) 99% GPU usage (video of the issue: https://drive.google.com/file/d/1pTucopKx6gvdlLOl4jW_LhzTMWXvqPxS/view?usp=sharing)

how to recreate (might not work on all PCs)
1. have tons of items
2. open inventory
3. see as the GPU drop and cause the framerate to drop below 10 (specifically for my specs)

I don't know why this is happening

Mods:
 - Minecraft Forge: [e.g. 14.23.5.2859]
 - HammerLib (HammerCore) [12.2.50]
 - Hammer Animations [12.2.33]
 - TerrariaCraft [12.6.2]
 - MusicLayer [12.2.22]
 - OpenCubicChunks [0.0.1271.0-SNAPSHOT-all]
 - ColoredLux [12.6.33]
(can't install optifine for some reason btw)
 
System:
 - CPU: Intel core i5 -2400 3.1Ghz
 - GPU: Nvidia Geforce GT 1030
 - RAM: 16GB  @ 1330Mhz
 - Java: ~~17~~ 8

**Comment by bigbumcletus** [comment] 2024-07-12 15:37
same thing with me and my friend

**Comment by Zeitheron** [comment] 2024-07-12 15:57
Duplicate of #120

**Closed as completed by Zeitheron** 2024-07-12 15:57 UTC
Labels: type: bug
