### ISSUE TITLE
Crash When Clicking UI Buttons

### ISSUE THREAD

**Issue by vizthex123** [TerrariaCraft/Issues#17] opened 2020-08-09 04:24 UTC
**Describe the bug**
I click "Done" or some other UI button, and the game crashes.

**To Reproduce**
1. Load game with mod
2. Edit your controls, or even just be in a world and pause the game then click one of the buttons
3. Game crashes

**Expected behavior**
Not crashing

**Mod Versions (please complete the following information):**
 - Minecraft Forge: 14.23.5.2847
 - HammerLib  2.0.6.19
 - TerrariaCraft 12.2.16
 - MusicLayer 12.2.20
 - OpenCubicChunks 0.0.1055.0-SNAPSHOT-all
 - Optifine Installed: Yes
 
 **Hardware & Software info (Might be important in some cases)**
 - CPU: Intel Core i7-4770k CPU @ 3.50 GHz
 - GPU: AMD Radon RTX 570
 - RAM: 16 GB
 - Java: Java 8 Update 261

**Additional context**
Could be something with another one of my mods, crash report attached
[crash-2020-08-08_23.18.23-client.txt](https://github.com/TerrariaCraft/Issues/files/5046760/crash-2020-08-08_23.18.23-client.txt)

**Comment by Zeitheron** [comment] 2020-08-09 10:36
Seems like duplicate of #15, has been fixed in dev

**Closed by Zeitheron** 2020-08-09 10:36 UTC
Labels: marker: duplicate, status: noticed, status: resolved, type: bug
